// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OverstromingsApp.Core;

#nullable disable

namespace OverstromingsApp.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OverstromingsApp.Core.Models.DataModel", b =>
                {
                    b.Property<int>("Jaar")
                        .HasColumnType("int");

                    b.Property<int>("Maand")
                        .HasColumnType("int");

                    b.Property<int>("NeerslagMM")
                        .HasColumnType("int");

                    b.HasKey("Jaar", "Maand");

                    b.ToTable("Neerslag");
                });
#pragma warning restore 612, 618
        }
    }
}
